enum AssistantIntent {
  balance,
  totalIncome,
  totalExpense,
  monthlyIncome,
  monthlyExpense,
  categoryExpense,
  topSpendingCategory,
  largestExpense,
  averageExpense,
  recentTransactions,
  dailyExpense,
  monthlyComparison,
  categoryComparison,
  spendingInsight,
  help,
  unknown,
}
